import React from 'react';
import {Metadata} from "next";

async function getData() {
    const res = await fetch('https://ifuw.ru/lotos/wp-json/api/products/all')
    // The return value is *not* serialized
    // You can return Date, Map, Set, etc.

    if (!res.ok) {
        // This will activate the closest `error.js` Error Boundary
        throw new Error('Failed to fetch data')
    }

    return res.json()
}

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const Page = () => {
    return (
        <main>
            
        </main>
    );
};

export default Page;